/**
 * Detect and strip C2PA / AI-related metadata from PNG, JPEG, WebP, AVIF, HEIC and GIF.
 *
 * TypeScript port of `js/image_meta.js` in ivanusto/unmark-web, which
 * is itself a port of the stdlib parsers in `service/scripts/image_meta.py` from
 * guillaumemeyer/watermarks-remover (MIT): same chunk/segment/box policy, same
 * marker heuristics, same VP8X flag fix-up. Pixels are never touched — this is
 * byte-level container surgery, not a canvas re-encode, so nothing is recompressed
 * and image quality is preserved exactly.
 *
 * tests/imageMeta.test.ts pins the output against values taken from that reference
 * implementation. Upstream changes still have to be pulled in by hand.
 */

export type ImageFormat = 'png' | 'jpeg' | 'webp' | 'avif' | 'heic' | 'gif' | 'unknown';

export interface InspectResult {
  format: ImageFormat;
  hasC2pa: boolean;
  hasAiMetadata: boolean;
  findings: string[];
}

export interface CleanResult {
  format: ImageFormat;
  data: Uint8Array;
  actions: string[];
}

const enc = new TextEncoder();
const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

const C2PA_MARKERS = [
  'c2pa', 'C2PA', 'jumb', 'JUMB', 'c2ma', 'contentcredentials', 'contentauth', 'cai:',
  'http://ns.adobe.com/xmp/InstanceID/',
];
const AI_META_HINTS = [
  'c2pa', 'C2PA', 'contentcredentials', 'ContentCredentials', 'digitalSourceType',
  'trainedAlgorithmicMedia', 'compositeWithTrainedAlgorithmicMedia', 'algorithmicMedia', 'AIGC', 'aigc',
  'AI generated', 'Generated by', 'Claude', 'Anthropic', 'OpenAI', 'SynthID', 'dcterms:provenance',
];
const ALL_HINTS = AI_META_HINTS.concat(C2PA_MARKERS);

/* Well-known AI generator product/model names. Matched ONLY against the values
 * of generator-bearing PNG text-chunk keys (Software, Creator, parameters) —
 * see generatorProductHits — and deliberately kept out of the flat ALL_HINTS
 * blob scan: bare "Gemini", "Sora" or "Firefly" are ordinary words that can
 * appear in captions, and only a generator field makes them evidence of AI
 * provenance. Folding them into ALL_HINTS would produce false positives and
 * diverge from the reference implementation. */
const AI_GENERATOR_PRODUCTS = [
  'ChatGPT', 'DALL-E', 'Midjourney', 'Stable Diffusion', 'SDXL', 'FLUX', 'DreamStudio', 'Leonardo AI',
  'Leonardo.Ai', 'Craiyon', 'NovelAI', 'Ideogram', 'TensorArt', 'Recraft', 'Clipdrop', 'DeepAI', 'NightCafe',
  'Bing Image Creator', 'Adobe Firefly', 'Firefly', 'Gemini', 'Imagen', 'Grok', 'Sora', 'Veo', 'Kling',
  'Runway', 'Luma', 'Qwen', 'GPT-4', 'GPT-5',
];

/* PNG text-chunk keys whose value can name the generating model/tool. tEXt and
 * iTXt "Software" and "Creator" are the classic generator fields; "parameters"
 * is what Stable Diffusion WebUI writes with the full generation string. Values
 * of other keys (Comment, Description, Title, ...) are free text and are never
 * scanned for product names. */
const GENERATOR_TEXT_KEYS = new Set(['software', 'creator', 'parameters']);
const C2PA_STRONG = new Set(['c2pa', 'contentcredentials', 'jumb', 'contentauth']);
const C2PA_STRONG_CORE = new Set(['c2pa', 'contentcredentials', 'jumb']);

const latin1 = (u8: Uint8Array): string => {
  let s = '';
  for (let i = 0; i < u8.length; i++) s += String.fromCharCode(u8[i]);
  return s;
};
const startsWith = (u8: Uint8Array, sig: number[]): boolean => sig.every((b, i) => u8[i] === b);
const be32 = (u8: Uint8Array, p: number): number =>
  ((u8[p] << 24) | (u8[p + 1] << 16) | (u8[p + 2] << 8) | u8[p + 3]) >>> 0;
const be16 = (u8: Uint8Array, p: number): number => (u8[p] << 8) | u8[p + 1];
const le32 = (u8: Uint8Array, p: number): number =>
  (u8[p] | (u8[p + 1] << 8) | (u8[p + 2] << 16) | (u8[p + 3] << 24)) >>> 0;
const packLe32 = (n: number): number[] => [n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff];
const packBe32 = (n: number): number[] => [(n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff];
const packBe64 = (n: number): number[] =>
  packBe32(Math.floor(n / 4294967296) >>> 0).concat(packBe32(n >>> 0));

/** Case-insensitive substring scan of a byte blob (latin-1 view), like upstream _contains_any. */
export function containsAny(u8: Uint8Array, needles: string[]): string[] {
  const lower = latin1(u8).toLowerCase();
  const found: string[] = [];
  for (const n of needles) if (lower.includes(n.toLowerCase())) found.push(n);
  return found;
}

const AVIF_BRANDS = ['avif', 'avis', 'avio'];
const HEIC_BRANDS = ['heic', 'heix', 'hevc', 'heim', 'heis', 'mif1', 'msf1', 'heif'];

export function detectFormat(u8: Uint8Array): ImageFormat {
  if (u8.length >= 8 && startsWith(u8, PNG_SIG)) return 'png';
  if (u8.length >= 2 && u8[0] === 0xff && u8[1] === 0xd8) return 'jpeg';
  if (u8.length >= 12 && latin1(u8.subarray(0, 4)) === 'RIFF' && latin1(u8.subarray(8, 12)) === 'WEBP') return 'webp';
  if (u8.length >= 12 && latin1(u8.subarray(4, 8)) === 'ftyp') {
    const boxSize = be32(u8, 0);
    // Brand match is case-sensitive here, unlike the marker heuristics below.
    const end = boxSize >= 8 ? Math.min(boxSize, u8.length, 64) : Math.min(u8.length, 64);
    const header = latin1(u8.subarray(8, Math.max(8, end)));
    if (AVIF_BRANDS.some((b) => header.includes(b))) return 'avif';
    if (HEIC_BRANDS.some((b) => header.includes(b))) return 'heic';
  }
  if (isGif(u8)) return 'gif';
  return 'unknown';
}

function concat(parts: Uint8Array[]): Uint8Array {
  let n = 0;
  for (const p of parts) n += p.length;
  const out = new Uint8Array(n);
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
}

/* Minimal synchronous DEFLATE (RFC 1951), with the optional zlib wrapper
 * (RFC 1950) skipped when present. The reference implementation reads PNG
 * zTXt/iTXt payloads with zlib.decompress; inspect()/clean() are synchronous
 * here and the only inflate a browser ships (DecompressionStream) is async, so
 * we carry our own rather than turn the whole API async.
 * Returns null on anything malformed — callers treat that exactly the way the
 * reference treats zlib.error: silently yield no entries, never raise. */
const INFLATE_MAX_OUTPUT = 16 * 1024 * 1024; // guards against zip bombs
const LEN_BASE = [3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115,
  131, 163, 195, 227, 258];
const LEN_EXTRA = [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0];
const DIST_BASE = [1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025,
  1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577];
const DIST_EXTRA = [0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12,
  12, 13, 13];
const CLEN_ORDER = [16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15];

interface HuffTable {
  counts: number[];
  sorted: number[];
  maxLen: number;
}

/* Canonical Huffman: how many codes exist per bit length, and the symbols
 * sorted by (length, symbol) — the classic counts/offsets form. */
function huffTable(lengths: number[]): HuffTable | null {
  let maxLen = 0;
  for (const l of lengths) if (l > maxLen) maxLen = l;
  if (maxLen === 0) return null;
  const counts = new Array(maxLen + 1).fill(0);
  for (const l of lengths) if (l) counts[l]++;
  const offsets = new Array(maxLen + 2).fill(0);
  for (let i = 1; i <= maxLen; i++) offsets[i + 1] = offsets[i] + counts[i];
  const sorted = new Array(offsets[maxLen + 1]);
  for (let sym = 0; sym < lengths.length; sym++) {
    if (lengths[sym]) sorted[offsets[lengths[sym]]++] = sym;
  }
  return { counts, sorted, maxLen };
}

let FIXED_LIT: HuffTable | null = null;
let FIXED_DIST: HuffTable | null = null;
function fixedTables(): [HuffTable | null, HuffTable | null] {
  if (!FIXED_LIT) {
    const lit = new Array(288);
    for (let i = 0; i < 288; i++) lit[i] = i < 144 ? 8 : i < 256 ? 9 : i < 280 ? 7 : 8;
    FIXED_LIT = huffTable(lit);
    FIXED_DIST = huffTable(new Array(30).fill(5));
  }
  return [FIXED_LIT, FIXED_DIST];
}

function inflate(u8: Uint8Array): Uint8Array | null {
  try {
    let pos = 0;
    // zlib wrapper: CM must be 8 and the 2-byte header is a multiple of 31.
    if (u8.length >= 2 && (u8[0] & 0x0f) === 8 && (((u8[0] << 8) | u8[1]) % 31) === 0) {
      if (u8[1] & 0x20) return null; // preset dictionary — not supported
      pos = 2;
    }
    let bitBuf = 0;
    let bitCnt = 0;
    let out = new Uint8Array(1024);
    let outLen = 0;

    const bits = (n: number): number => {
      if (n === 0) return 0;
      while (bitCnt < n) {
        if (pos >= u8.length) throw new Error('eof');
        bitBuf |= u8[pos++] << bitCnt;
        bitCnt += 8;
      }
      const v = bitBuf & ((1 << n) - 1);
      bitBuf >>>= n;
      bitCnt -= n;
      return v;
    };
    const decode = (t: HuffTable | null): number => {
      if (!t) throw new Error('no table');
      let code = 0;
      let first = 0;
      let index = 0;
      for (let len = 1; len <= t.maxLen; len++) {
        code |= bits(1);
        const count = t.counts[len];
        if (code - first < count) return t.sorted[index + (code - first)];
        index += count;
        first = (first + count) << 1;
        code <<= 1;
      }
      throw new Error('bad code');
    };
    const grow = (extra: number): void => {
      if (outLen + extra <= out.length) return;
      if (outLen + extra > INFLATE_MAX_OUTPUT) throw new Error('too large');
      let cap = out.length;
      while (cap < outLen + extra) cap *= 2;
      const next = new Uint8Array(Math.min(cap, INFLATE_MAX_OUTPUT));
      next.set(out.subarray(0, outLen));
      out = next;
    };

    for (;;) {
      const final = bits(1);
      const type = bits(2);
      if (type === 0) {
        // Stored: the partial byte is dropped, then LEN/NLEN come raw.
        bitBuf = 0;
        bitCnt = 0;
        if (pos + 4 > u8.length) throw new Error('eof');
        const len = u8[pos] | (u8[pos + 1] << 8);
        const nlen = u8[pos + 2] | (u8[pos + 3] << 8);
        pos += 4;
        if ((len ^ 0xffff) !== nlen) throw new Error('bad stored block');
        if (pos + len > u8.length) throw new Error('eof');
        grow(len);
        out.set(u8.subarray(pos, pos + len), outLen);
        outLen += len;
        pos += len;
      } else if (type === 1 || type === 2) {
        let litTable: HuffTable | null;
        let distTable: HuffTable | null;
        if (type === 1) {
          [litTable, distTable] = fixedTables();
        } else {
          const hlit = bits(5) + 257;
          const hdist = bits(5) + 1;
          const hclen = bits(4) + 4;
          const clens = new Array(19).fill(0);
          for (let i = 0; i < hclen; i++) clens[CLEN_ORDER[i]] = bits(3);
          const clTable = huffTable(clens);
          const lengths = new Array(hlit + hdist).fill(0);
          for (let i = 0; i < lengths.length; ) {
            const sym = decode(clTable);
            if (sym < 16) {
              lengths[i++] = sym;
              continue;
            }
            let repeat: number;
            let value = 0;
            if (sym === 16) {
              if (i === 0) throw new Error('bad repeat');
              value = lengths[i - 1];
              repeat = 3 + bits(2);
            } else if (sym === 17) {
              repeat = 3 + bits(3);
            } else {
              repeat = 11 + bits(7);
            }
            if (i + repeat > lengths.length) throw new Error('bad repeat');
            for (let k = 0; k < repeat; k++) lengths[i++] = value;
          }
          litTable = huffTable(lengths.slice(0, hlit));
          distTable = huffTable(lengths.slice(hlit));
        }
        for (;;) {
          const sym = decode(litTable);
          if (sym === 256) break;
          if (sym < 256) {
            grow(1);
            out[outLen++] = sym;
            continue;
          }
          const li = sym - 257;
          if (li >= LEN_BASE.length) throw new Error('bad length code');
          const length = LEN_BASE[li] + bits(LEN_EXTRA[li]);
          const di = decode(distTable);
          if (di >= DIST_BASE.length) throw new Error('bad distance code');
          const dist = DIST_BASE[di] + bits(DIST_EXTRA[di]);
          if (dist > outLen) throw new Error('distance too far back');
          grow(length);
          for (let k = 0; k < length; k++) {
            out[outLen] = out[outLen - dist];
            outLen++;
          }
        }
      } else {
        throw new Error('reserved block type');
      }
      if (final) break;
    }
    return out.subarray(0, outLen);
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------- PNG
interface PngChunk {
  type: string;
  truncated?: boolean;
  /** Byte offset of the chunk header, present only when truncated. */
  offset?: number;
  payload?: Uint8Array;
  raw?: Uint8Array;
}

function* pngChunks(u8: Uint8Array): Generator<PngChunk> {
  let pos = 8;
  while (pos + 8 <= u8.length) {
    const length = be32(u8, pos);
    const type = latin1(u8.subarray(pos + 4, pos + 8));
    const start = pos + 8;
    const end = start + length;
    if (end + 4 > u8.length) {
      yield { type, truncated: true, offset: pos };
      return;
    }
    yield { type, payload: u8.subarray(start, end), raw: u8.subarray(pos, end + 4) };
    if (type === 'IEND') return;
    pos = end + 4;
  }
}

const utf8Dec = new TextDecoder('utf-8');

/* Parse a PNG text-chunk payload into [key, value] pairs. Handles tEXt
 * (latin-1), zTXt (zlib-compressed text) and iTXt (UTF-8, optionally
 * compressed). Malformed or undecodable chunks yield whatever pairs are
 * recoverable; nothing is thrown. */
function pngTextEntries(payload: Uint8Array, ctype: string): Array<[string, string]> {
  const nul = payload.indexOf(0);
  if (nul < 0) return [];
  const key = latin1(payload.subarray(0, nul));
  const rest = payload.subarray(nul + 1);
  if (ctype === 'tEXt') return [[key, latin1(rest)]];
  if (ctype === 'zTXt') {
    if (rest.length < 2) return [];
    const text = inflate(rest.subarray(1)); // skip the compression-method byte
    if (text === null) return [];
    return [[key, latin1(text)]];
  }
  if (ctype === 'iTXt') {
    if (rest.length < 4) return [];
    const compFlag = rest[0];
    let r = rest.subarray(2); // skip compression flag + method
    const langEnd = r.indexOf(0);
    if (langEnd < 0) return [];
    r = r.subarray(langEnd + 1);
    const tkeyEnd = r.indexOf(0);
    if (tkeyEnd < 0) return [];
    let text: Uint8Array | null = r.subarray(tkeyEnd + 1);
    if (compFlag === 1) {
      text = inflate(text);
      if (text === null) return [];
    }
    return [[key, utf8Dec.decode(text)]];
  }
  return [];
}

/* Product-name hits scoped to generator-bearing text-chunk keys. Returns labels
 * like "Software=ChatGPT". Case-insensitive substring match on the value,
 * mirroring containsAny but only for GENERATOR_TEXT_KEYS. */
function generatorProductHits(entries: Array<[string, string]>): string[] {
  const hits: string[] = [];
  for (const [key, value] of entries) {
    const k = key.trim();
    if (!GENERATOR_TEXT_KEYS.has(k.toLowerCase())) continue;
    const low = value.toLowerCase();
    for (const product of AI_GENERATOR_PRODUCTS) {
      if (low.includes(product.toLowerCase())) hits.push(`${k}=${product}`);
    }
  }
  return hits;
}

/* Flat-marker and product-name hits from a PNG text chunk. Flat markers are
 * matched against the raw payload *and* the decoded text, so a marker that only
 * exists inside a compressed zTXt/iTXt payload is still caught. */
function pngTextHits(payload: Uint8Array, ctype: string): [string[], string[]] {
  const entries = pngTextEntries(payload, ctype);
  const decoded = enc.encode(entries.map(([, value]) => value).join('\n'));
  const blob = concat([payload, new Uint8Array([0x0a]), decoded]);
  return [containsAny(blob, ALL_HINTS), generatorProductHits(entries)];
}

/* True when a PNG text chunk carries AI/C2PA markers. Flat markers match the
 * raw payload and decoded text; generator product names only match the values
 * of generator-bearing keys. */
function textChunkIsAi(payload: Uint8Array, ctype: string): boolean {
  const [hits, productHits] = pngTextHits(payload, ctype);
  return hits.length > 0 || productHits.length > 0;
}

export function inspectPng(u8: Uint8Array): Omit<InspectResult, 'format'> {
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAiMetadata = false;
  if (detectFormat(u8) !== 'png') return { hasC2pa: false, hasAiMetadata: false, findings: ['not a PNG'] };
  for (const c of pngChunks(u8)) {
    if (c.truncated) {
      // The reference renders the chunk type with Python's repr(), so the
      // b'...' wrapper is part of the finding string the goldens pin.
      findings.push(`truncated chunk b'${c.type}'`);
      break;
    }
    if (c.type === 'caBX' || c.type === 'juMB' || c.type === 'jumb' || c.type.startsWith('c2')) {
      hasC2pa = true;
      findings.push(`PNG chunk ${c.type} (possible C2PA container)`);
    }
    if (['tEXt', 'zTXt', 'iTXt', 'eXIf'].includes(c.type)) {
      // eXIf is deliberately excluded from product matching: it holds no PNG
      // text keys to scope by, and no text to decode.
      const [hits, productHits] =
        c.type === 'eXIf'
          ? [containsAny(c.payload as Uint8Array, ALL_HINTS), [] as string[]]
          : pngTextHits(c.payload as Uint8Array, c.type);
      if (hits.length || productHits.length) {
        hasAiMetadata = true;
        if (hits.some((h) => C2PA_STRONG_CORE.has(h.toLowerCase()))) hasC2pa = true;
        const parts = hits.length ? [hits.slice(0, 8).join(', ')] : [];
        if (productHits.length) parts.push(`AI generator (${productHits.slice(0, 8).join(', ')})`);
        findings.push(`PNG ${c.type}: ${parts.join('; ')}`);
      }
    }
  }
  const whole = containsAny(u8, C2PA_MARKERS);
  if (whole.length && !hasC2pa) {
    hasC2pa = true;
    findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(', ')}`);
  }
  return { hasC2pa, hasAiMetadata: hasAiMetadata || hasC2pa, findings };
}

const PNG_STRUCTURAL = new Set(['IHDR', 'IDAT', 'IEND', 'PLTE', 'tRNS', 'gAMA', 'pHYs', 'sRGB', 'cHRM', 'iCCP']);

export function stripPng(u8: Uint8Array, { stripAllText = true }: { stripAllText?: boolean } = {}): Omit<CleanResult, 'format'> {
  if (detectFormat(u8) !== 'png') throw new Error('not PNG');
  const actions: string[] = [];
  const out: Uint8Array[] = [new Uint8Array(PNG_SIG)];
  for (const c of pngChunks(u8)) {
    if (c.truncated) {
      // A truncated chunk (an interrupted download or a half-written upload):
      // copy the remainder verbatim instead of dropping it. Dropping turned a
      // recoverable image into an unopenable husk while reporting it as already
      // clean (upstream watermarks-remover#170). Recorded as an action so the
      // run is never mistaken for an ordinary no-op clean.
      const at = c.offset as number;
      out.push(u8.subarray(at));
      actions.push(`kept ${u8.length - at} bytes of truncated chunk ${c.type} tail (file truncated)`);
      break;
    }
    let drop = false;
    if (c.type === 'eXIf' || c.type === 'caBX' || c.type.startsWith('c2')) {
      drop = true;
      actions.push(`drop chunk ${c.type}`);
    } else if (['tEXt', 'zTXt', 'iTXt'].includes(c.type)) {
      if (stripAllText || textChunkIsAi(c.payload as Uint8Array, c.type)) {
        drop = true;
        actions.push(`drop chunk ${c.type}`);
      }
    } else if (
      !PNG_STRUCTURAL.has(c.type) &&
      containsAny(concat([enc.encode(c.type), c.payload as Uint8Array]), C2PA_MARKERS).length
    ) {
      drop = true;
      actions.push(`drop chunk ${c.type} (C2PA marker in payload)`);
    }
    if (!drop) out.push(c.raw as Uint8Array);
  }
  if (!actions.length) actions.push('no PNG metadata chunks removed (already clean or none matched)');
  return { data: concat(out), actions };
}

// ---------------------------------------------------------------- JPEG
export function inspectJpeg(u8: Uint8Array): Omit<InspectResult, 'format'> {
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAiMetadata = false;
  if (detectFormat(u8) !== 'jpeg') return { hasC2pa: false, hasAiMetadata: false, findings: ['not a JPEG'] };
  let i = 2;
  const n = u8.length;
  while (i + 4 <= n) {
    if (u8[i] !== 0xff) {
      i++;
      continue;
    }
    while (i < n && u8[i] === 0xff) i++;
    if (i >= n) break;
    const marker = u8[i];
    i++;
    if (marker === 0xd8 || marker === 0xd9) continue;
    if (marker === 0xda) break;
    if (marker >= 0xd0 && marker <= 0xd7) continue;
    if (i + 2 > n) break;
    const seglen = be16(u8, i);
    if (seglen < 2 || i + seglen > n) {
      findings.push(`bad segment length at marker 0x${marker.toString(16).toUpperCase()}`);
      break;
    }
    const payload = u8.subarray(i + 2, i + seglen);
    i += seglen;
    if (marker === 0xeb) {
      hasC2pa = true;
      findings.push('JPEG APP11 segment (JUMBF/C2PA common)');
    }
    if ([0xe1, 0xe2, 0xed, 0xee, 0xeb].includes(marker)) {
      const hits = containsAny(payload, ALL_HINTS);
      if (hits.length) {
        hasAiMetadata = true;
        if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
        findings.push(`JPEG APP${marker - 0xe0}: ${hits.slice(0, 8).join(', ')}`);
      }
    }
  }
  const whole = containsAny(u8, C2PA_MARKERS);
  if (whole.length && !hasC2pa) {
    hasC2pa = true;
    findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(', ')}`);
  }
  return { hasC2pa, hasAiMetadata: hasAiMetadata || hasC2pa, findings };
}

export function stripJpeg(u8: Uint8Array, { stripAllApp = true }: { stripAllApp?: boolean } = {}): Omit<CleanResult, 'format'> {
  if (detectFormat(u8) !== 'jpeg') throw new Error('not JPEG');
  const actions: string[] = [];
  const out: Uint8Array[] = [new Uint8Array([0xff, 0xd8])];
  let i = 2;
  const n = u8.length;
  while (i < n) {
    if (u8[i] !== 0xff) {
      out.push(u8.subarray(i));
      actions.push('copied remainder after non-marker byte');
      break;
    }
    while (i < n && u8[i] === 0xff) i++;
    if (i >= n) break;
    const marker = u8[i];
    i++;
    if (marker === 0xd9) {
      out.push(new Uint8Array([0xff, 0xd9]));
      break;
    }
    if (marker === 0xd8) continue;
    if (marker >= 0xd0 && marker <= 0xd7) {
      out.push(new Uint8Array([0xff, marker]));
      continue;
    }
    if (marker === 0xda) {
      if (i + 2 > n) break;
      out.push(new Uint8Array([0xff, 0xda]));
      out.push(u8.subarray(i));
      actions.push('preserved entropy-coded scan (SOS→EOF)');
      break;
    }
    if (i + 2 > n) break;
    const seglen = be16(u8, i);
    if (seglen < 2 || i + seglen > n) {
      out.push(u8.subarray(i - 2));
      actions.push('truncated segment; copied remainder');
      break;
    }
    const payload = u8.subarray(i + 2, i + seglen);
    let keep = false;
    let drop = false;
    if (marker >= 0xe0 && marker <= 0xef) {
      if (marker === 0xeb) {
        drop = true;
        actions.push('drop APP11 (C2PA/JUMBF)');
      } else if (stripAllApp && marker !== 0xe0) {
        drop = true;
        actions.push(`drop APP${marker - 0xe0}`);
      } else if (containsAny(payload, ALL_HINTS).length) {
        drop = true;
        actions.push(`drop APP${marker - 0xe0} (AI/C2PA markers)`);
      } else {
        keep = true;
      }
    } else if (marker === 0xfe) {
      drop = true;
      actions.push('drop COM comment');
    } else {
      keep = true;
    }
    if (keep && !drop) {
      out.push(new Uint8Array([0xff, marker]));
      out.push(u8.subarray(i, i + seglen));
    }
    i += seglen;
  }
  if (!actions.length) actions.push('no JPEG APP segments removed');
  return { data: concat(out), actions };
}

// ---------------------------------------------------------------- WebP
interface WebpChunk {
  fourcc: string;
  payload: Uint8Array;
  padding: Uint8Array;
}

function webpChunks(u8: Uint8Array): { chunks: WebpChunk[]; notes: string[] } {
  if (detectFormat(u8) !== 'webp') return { chunks: [], notes: ['not a WebP'] };
  const notes: string[] = [];
  const declared = le32(u8, 4);
  if (declared + 8 !== u8.length) notes.push(`RIFF size mismatch: header=${declared + 8} actual=${u8.length}`);
  const chunks: WebpChunk[] = [];
  let pos = 12;
  while (pos + 8 <= u8.length) {
    const fourcc = latin1(u8.subarray(pos, pos + 4));
    const length = le32(u8, pos + 4);
    const ps = pos + 8;
    const pe = ps + length;
    const padded = pe + (length & 1);
    if (padded > u8.length) {
      notes.push(`truncated WebP chunk ${fourcc}`);
      break;
    }
    chunks.push({ fourcc, payload: u8.subarray(ps, pe), padding: u8.subarray(pe, padded) });
    pos = padded;
  }
  if (pos !== u8.length && !notes.some((x) => x.includes('truncated'))) {
    notes.push(`trailing WebP bytes: ${u8.length - pos}`);
  }
  return { chunks, notes };
}

export function inspectWebp(u8: Uint8Array): Omit<InspectResult, 'format'> {
  const { chunks, notes } = webpChunks(u8);
  const findings = notes.slice();
  if (!chunks.length && notes[0] === 'not a WebP') return { hasC2pa: false, hasAiMetadata: false, findings };
  let hasC2pa = false;
  let hasAiMetadata = false;
  for (const c of chunks) {
    if (c.fourcc.toUpperCase() === 'C2PA') {
      hasC2pa = true;
      hasAiMetadata = true;
      findings.push('WebP C2PA chunk');
      continue;
    }
    if (c.fourcc === 'XMP ' || c.fourcc === 'EXIF') {
      const hits = containsAny(c.payload, ALL_HINTS);
      if (hits.length) {
        hasAiMetadata = true;
        if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
        findings.push(`WebP ${c.fourcc}: ${hits.slice(0, 8).join(', ')}`);
      }
    }
  }
  return { hasC2pa, hasAiMetadata: hasAiMetadata || hasC2pa, findings };
}

const WEBP_META_FLAGS: Record<string, number> = { ICCP: 0x20, EXIF: 0x08, 'XMP ': 0x04 };

export function stripWebp(
  u8: Uint8Array,
  { stripAllMetadata = true }: { stripAllMetadata?: boolean } = {}
): Omit<CleanResult, 'format'> {
  const { chunks, notes } = webpChunks(u8);
  if (!chunks.length && notes[0] === 'not a WebP') throw new Error('not WebP');
  if (notes.length) throw new Error('malformed WebP: ' + notes.join('; '));
  const actions: string[] = [];
  const kept: WebpChunk[] = [];
  let removedFlags = 0;
  for (const c of chunks) {
    let drop = c.fourcc.toUpperCase() === 'C2PA';
    if (c.fourcc in WEBP_META_FLAGS) drop = stripAllMetadata || containsAny(c.payload, ALL_HINTS).length > 0;
    if (drop) {
      actions.push(`drop WebP chunk ${c.fourcc}`);
      removedFlags |= WEBP_META_FLAGS[c.fourcc] || 0;
    } else {
      kept.push(c);
    }
  }
  const body: Uint8Array[] = [enc.encode('WEBP')];
  for (const c of kept) {
    let payload = c.payload;
    if (c.fourcc === 'VP8X' && payload.length >= 1 && removedFlags) {
      payload = new Uint8Array(payload);
      payload[0] &= ~removedFlags;
    }
    body.push(enc.encode(c.fourcc), new Uint8Array(packLe32(payload.length)), payload);
    if (payload.length & 1) body.push(c.padding.length ? c.padding : new Uint8Array([0]));
  }
  const bodyBytes = concat(body);
  if (!actions.length) actions.push('no WebP metadata chunks removed (already clean or none matched)');
  return { data: concat([enc.encode('RIFF'), new Uint8Array(packLe32(bodyBytes.length)), bodyBytes]), actions };
}

// ------------------------------------------------------- AVIF / HEIC (ISOBMFF)
const XMP_UUID = [0xbe, 0x7a, 0xcf, 0xcb, 0x97, 0xa9, 0x42, 0xe8, 0x9c, 0x71, 0x99, 0x94, 0x91, 0xe3, 0xaf, 0xac];

interface IsoBox {
  fourcc: string;
  payload: Uint8Array;
  size: number;
  headerSize: number;
}

/**
 * Parse top-level or container boxes.
 *
 * `scannedEnd` is the offset the walk stopped at: the start of the first box
 * that could not be parsed (one whose declared size overruns the data, or a run
 * of fewer than 8 trailing bytes), or `end` when the whole buffer parsed.
 */
function parseIsobmffBoxes(
  u8: Uint8Array,
  start = 0,
  end: number | null = null
): { boxes: IsoBox[]; scannedEnd: number } {
  if (end === null) end = u8.length;
  const boxes: IsoBox[] = [];
  let pos = start;
  while (pos + 8 <= end) {
    let size = be32(u8, pos);
    const fourcc = latin1(u8.subarray(pos + 4, pos + 8));
    let headerSize = 8;
    if (size === 1) {
      if (pos + 16 > end) break;
      size = be32(u8, pos + 8) * 4294967296 + be32(u8, pos + 12);
      headerSize = 16;
    } else if (size === 0) {
      size = end - pos;
    }
    if (size < headerSize || pos + size > end) break;
    boxes.push({ fourcc, payload: u8.subarray(pos + headerSize, pos + size), size, headerSize });
    pos += size;
  }
  return { boxes, scannedEnd: pos };
}

const isC2paBox = (fourcc: string): boolean =>
  fourcc === 'jumb' || fourcc === 'c2pa' || fourcc.toLowerCase().startsWith('c2');
const isXmpUuid = (payload: Uint8Array): boolean =>
  payload.length >= 16 && XMP_UUID.every((b, i) => payload[i] === b);

export function inspectIsobmff(u8: Uint8Array, fmt: string): Omit<InspectResult, 'format'> {
  const F = fmt.toUpperCase();
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAiMetadata = false;
  const { boxes } = parseIsobmffBoxes(u8);
  if (!boxes.length) {
    // Box parsing failed, typically because the first box's size overruns a
    // truncated download. That is exactly when the whole-file byte scan is most
    // useful, and every sibling inspector still runs its equivalent after a
    // truncation, so run it here too and report the parse failure alongside
    // whatever it found (upstream watermarks-remover#167).
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length) {
      hasC2pa = true;
      findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(', ')}`);
    }
    findings.push(`not a valid ${F} (no ISOBMFF boxes found)`);
    return { hasC2pa, hasAiMetadata: hasAiMetadata || hasC2pa, findings };
  }

  const strong = (hits: string[], set: Set<string>): boolean => hits.some((h) => set.has(h.toLowerCase()));

  for (const { fourcc, payload } of boxes) {
    if (isC2paBox(fourcc)) {
      hasC2pa = true;
      findings.push(`${F} top-level box ${fourcc} (C2PA/JUMBF manifest)`);
    } else if (fourcc === 'uuid') {
      if (isXmpUuid(payload)) {
        hasAiMetadata = true;
        const hits = containsAny(payload.subarray(16), ALL_HINTS);
        findings.push(hits.length ? `${F} XMP uuid box: ${hits.slice(0, 8).join(', ')}` : `${F} XMP uuid box`);
        if (strong(hits, C2PA_STRONG)) hasC2pa = true;
      } else {
        const hits = containsAny(payload, ALL_HINTS);
        if (hits.length) {
          hasAiMetadata = true;
          findings.push(`${F} uuid box: ${hits.slice(0, 8).join(', ')}`);
          if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
        }
      }
    } else if (fourcc === 'meta') {
      for (const sub of parseIsobmffBoxes(payload, 4).boxes) {
        const sName = sub.fourcc;
        if (isC2paBox(sName)) {
          hasC2pa = true;
          findings.push(`${F} meta sub-box ${sName} (C2PA/JUMBF container)`);
        } else if (sName === 'uuid') {
          if (isXmpUuid(sub.payload)) {
            hasAiMetadata = true;
            const hits = containsAny(sub.payload.subarray(16), ALL_HINTS);
            findings.push(hits.length ? `${F} meta XMP uuid: ${hits.slice(0, 8).join(', ')}` : `${F} meta XMP uuid box`);
            if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
          } else {
            const hits = containsAny(sub.payload, ALL_HINTS);
            if (hits.length) {
              hasAiMetadata = true;
              findings.push(`${F} meta uuid: ${hits.slice(0, 8).join(', ')}`);
            }
          }
        } else if (['iinf', 'infe', 'iref', 'iloc', 'xml ', 'bxml'].includes(sName)) {
          const hits = containsAny(sub.payload, ALL_HINTS);
          if (hits.length) {
            hasAiMetadata = true;
            if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
            findings.push(`${F} meta/${sName}: ${hits.slice(0, 8).join(', ')}`);
          }
        }
      }
    }
  }

  const whole = containsAny(u8, C2PA_MARKERS);
  if (whole.length && !hasC2pa) {
    hasC2pa = true;
    findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(', ')}`);
  }
  return { hasC2pa, hasAiMetadata: hasAiMetadata || hasC2pa, findings };
}

/**
 * Serialize an ISOBMFF box, preserving the width of its original header so a
 * 64-bit box stays 64-bit and every later absolute offset keeps its meaning.
 */
function buildIsobmffBox(fourcc: string, payload: Uint8Array, headerSize = 8): Uint8Array {
  const size = payload.length + headerSize;
  const head =
    headerSize === 16
      ? packBe32(1).concat([...enc.encode(fourcc)], packBe64(size))
      : packBe32(size).concat([...enc.encode(fourcc)]);
  return concat([new Uint8Array(head), payload]);
}

/**
 * An equal-size `free` box to put where a dropped box used to be. Rewriting in
 * place instead of closing the gap is what keeps absolute media offsets valid
 * (upstream watermarks-remover#183), so a cleaned AVIF or HEIC keeps its length.
 */
const isobmffFreeBox = (size: number, headerSize = 8): Uint8Array =>
  buildIsobmffBox('free', new Uint8Array(size - headerSize), headerSize);

export function stripIsobmff(
  u8: Uint8Array,
  fmt: string,
  { stripAllMetadata = true }: { stripAllMetadata?: boolean } = {}
): Omit<CleanResult, 'format'> {
  const F = fmt.toUpperCase();
  const { boxes, scannedEnd } = parseIsobmffBoxes(u8);
  if (!boxes.length) throw new Error(`not a valid ${F} (no ISOBMFF boxes)`);
  // scannedEnd is where the box walk stopped: the parser halts at the first box
  // whose declared size overruns the data. The rebuild below used to emit only
  // the boxes that parsed, dropping a truncated mdat (the actual coded image)
  // while reporting the file as already clean (upstream watermarks-remover#170);
  // the tail is appended verbatim afterwards instead.
  const actions: string[] = [];
  const out: Uint8Array[] = [];

  for (const { fourcc, payload, size, headerSize } of boxes) {
    if (isC2paBox(fourcc)) {
      actions.push(`drop top-level ${fourcc} box (C2PA/JUMBF)`);
      out.push(isobmffFreeBox(size, headerSize));
      continue;
    }

    if (fourcc === 'uuid') {
      if (isXmpUuid(payload)) {
        actions.push(`drop top-level ${fourcc} box (XMP metadata)`);
        out.push(isobmffFreeBox(size, headerSize));
        continue;
      }
      if (stripAllMetadata || containsAny(payload, ALL_HINTS).length) {
        actions.push(`drop top-level ${fourcc} box (UUID metadata)`);
        out.push(isobmffFreeBox(size, headerSize));
        continue;
      }
    }

    if (fourcc === 'meta') {
      const verflags = payload.length >= 4 ? payload.subarray(0, 4) : new Uint8Array(4);
      const cleanSub: Uint8Array[] = [];
      for (const sub of parseIsobmffBoxes(payload, 4).boxes) {
        const sName = sub.fourcc;
        if (isC2paBox(sName)) {
          actions.push(`drop meta sub-box ${sName} (C2PA/JUMBF)`);
          cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize));
          continue;
        }
        if (sName === 'uuid') {
          if (isXmpUuid(sub.payload)) {
            actions.push(`drop meta sub-box ${sName} (XMP metadata)`);
            cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize));
            continue;
          }
          if (stripAllMetadata || containsAny(sub.payload, ALL_HINTS).length) {
            actions.push(`drop meta sub-box ${sName} (UUID metadata)`);
            cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize));
            continue;
          }
        }
        if (sName === 'xml ' || sName === 'bxml') {
          if (stripAllMetadata || containsAny(sub.payload, ALL_HINTS).length) {
            actions.push(`drop meta sub-box ${sName} (XML metadata)`);
            cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize));
            continue;
          }
        }
        cleanSub.push(buildIsobmffBox(sName, sub.payload, sub.headerSize));
      }
      out.push(buildIsobmffBox('meta', concat([verflags, concat(cleanSub)]), headerSize));
      continue;
    }

    out.push(buildIsobmffBox(fourcc, payload, headerSize));
  }

  if (scannedEnd < u8.length) {
    const tail = u8.subarray(scannedEnd);
    out.push(tail);
    // An 8-byte header whose box overruns the data is a truncated download worth
    // reporting; fewer than 8 leftover bytes is merely trailing junk, kept
    // verbatim without claiming the file was truncated.
    if (tail.length >= 8) actions.push(`kept ${tail.length} bytes of truncated tail (file truncated)`);
  }

  if (!actions.length) actions.push(`no ${F} metadata boxes removed (already clean or none matched)`);
  return { data: concat(out), actions };
}

// ---------------------------------------------------------------- GIF
const GIF_XMP_APPLICATION_ID = 'XMP DataXMP';
// Application extensions that control rendering rather than carrying provenance;
// dropping them would change animation looping or color.
const GIF_CONTROL_APPLICATION_IDS = ['NETSCAPE2.0', 'ICCRGBG1012'];

const isGif = (u8: Uint8Array): boolean =>
  u8.length >= 6 && (latin1(u8.subarray(0, 6)) === 'GIF87a' || latin1(u8.subarray(0, 6)) === 'GIF89a');

interface GifExtension {
  end: number;
  label: number;
  payload: Uint8Array;
}

/** The extension block at `start` (0x21), or null when truncated. */
function gifExtensionInfo(u8: Uint8Array, start: number, n: number): GifExtension | null {
  if (start + 2 > n) return null;
  const label = u8[start + 1];
  let pos = start + 2;
  const parts: Uint8Array[] = [];
  while (pos < n) {
    const size = u8[pos];
    pos += 1;
    if (size === 0) return { end: pos, label, payload: concat(parts) };
    if (pos + size > n) return null;
    parts.push(u8.subarray(pos, pos + size));
    pos += size;
  }
  return null;
}

/** Offset just past the image block starting at `start` (0x2C), or null. */
function gifImageEnd(u8: Uint8Array, start: number, n: number): number | null {
  let pos = start + 1;
  if (pos + 9 > n) return null;
  const packed = u8[pos + 8];
  pos += 9;
  if (packed & 0x80) pos += 3 * (1 << ((packed & 0x07) + 1)); // local color table
  if (pos >= n) return null;
  pos += 1; // LZW minimum code size
  while (pos < n) {
    const size = u8[pos];
    pos += 1;
    if (size === 0) return pos;
    if (pos + size > n) return null;
    pos += size;
  }
  return null;
}

export function inspectGif(u8: Uint8Array): Omit<InspectResult, 'format'> {
  if (!isGif(u8)) return { hasC2pa: false, hasAiMetadata: false, findings: ['not a GIF'] };
  const findings: string[] = [];
  let hasC2pa = false;
  let hasAi = false;
  const n = u8.length;
  let pos = 6;
  if (pos + 7 > n) return { hasC2pa: false, hasAiMetadata: false, findings: ['truncated GIF header'] };
  const packed = u8[pos + 4];
  pos += 7;
  if (packed & 0x80) pos += 3 * (1 << ((packed & 0x07) + 1)); // global color table
  while (pos < n) {
    const block = u8[pos];
    if (block === 0x3b) break; // trailer
    if (block === 0x21) {
      const info = gifExtensionInfo(u8, pos, n);
      if (info === null) {
        findings.push('truncated GIF extension');
        break;
      }
      const { end, label, payload } = info;
      if (label === 0xfe) {
        findings.push('GIF comment extension present');
        const hits = containsAny(payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          findings.push(`GIF comment: ${hits.slice(0, 6).join(', ')}`);
        }
      } else if (label === 0xff) {
        const ident = latin1(payload.subarray(0, 11));
        if (ident === GIF_XMP_APPLICATION_ID) {
          findings.push('GIF XMP application extension present');
          const hits = containsAny(payload, ALL_HINTS);
          if (hits.length) {
            hasAi = true;
            findings.push(`GIF XMP: ${hits.slice(0, 6).join(', ')}`);
          }
        } else if (['c2pa', 'jumb', 'C2PA', 'JUMB'].some((m) => ident.includes(m))) {
          hasC2pa = true;
          findings.push('GIF application extension (possible C2PA)');
        }
      }
      pos = end;
    } else if (block === 0x2c) {
      const end = gifImageEnd(u8, pos, n);
      if (end === null) {
        findings.push('truncated GIF image block');
        break;
      }
      pos = end;
    } else {
      pos += 1;
    }
  }
  const whole = containsAny(u8, C2PA_MARKERS);
  if (whole.length && !hasC2pa) {
    hasC2pa = true;
    findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(', ')}`);
  }
  if (!findings.length) findings.push('no GIF metadata extensions found');
  return { hasC2pa, hasAiMetadata: hasAi || hasC2pa, findings };
}

export function stripGif(
  u8: Uint8Array,
  { stripAllMetadata = true }: { stripAllMetadata?: boolean } = {},
): Omit<CleanResult, 'format'> {
  if (!isGif(u8)) throw new Error('not GIF');
  const actions: string[] = [];
  const parts: Uint8Array[] = [u8.subarray(0, 6)];
  const n = u8.length;
  let pos = 6;
  if (pos + 7 > n) throw new Error('truncated GIF header');
  const packed = u8[pos + 4];
  parts.push(u8.subarray(pos, pos + 7));
  pos += 7;
  if (packed & 0x80) {
    const gctSize = 3 * (1 << ((packed & 0x07) + 1));
    parts.push(u8.subarray(pos, pos + gctSize));
    pos += gctSize;
  }
  while (pos < n) {
    const block = u8[pos];
    if (block === 0x3b) {
      parts.push(u8.subarray(pos)); // trailer
      break;
    }
    if (block === 0x21) {
      const info = gifExtensionInfo(u8, pos, n);
      if (info === null) {
        parts.push(u8.subarray(pos));
        break;
      }
      const { end, label, payload } = info;
      let drop = false;
      let name = 'extension';
      if (label === 0xfe) {
        name = 'comment';
        drop = stripAllMetadata || containsAny(payload, ALL_HINTS).length > 0;
      } else if (label === 0xff) {
        const ident = latin1(payload.subarray(0, 11));
        const markerHit = containsAny(payload, ALL_HINTS).length > 0;
        if (ident === GIF_XMP_APPLICATION_ID) {
          name = 'XMP application';
          drop = stripAllMetadata || markerHit;
        } else if (GIF_CONTROL_APPLICATION_IDS.includes(ident)) {
          name = 'control application';
          drop = markerHit; // keep looping/ICC unless it carries markers
        } else {
          name = 'application';
          drop = stripAllMetadata || markerHit;
        }
      }
      if (drop) actions.push(`drop GIF ${name} extension`);
      else parts.push(u8.subarray(pos, end));
      pos = end;
    } else if (block === 0x2c) {
      const end = gifImageEnd(u8, pos, n);
      if (end === null) {
        parts.push(u8.subarray(pos));
        break;
      }
      parts.push(u8.subarray(pos, end));
      pos = end;
    } else {
      parts.push(u8.subarray(pos, pos + 1));
      pos += 1;
    }
  }
  if (!actions.length) actions.push('no GIF metadata blocks removed (already clean or none matched)');
  return { data: concat(parts), actions };
}

// ---------------------------------------------------------------- unified
export function inspect(u8: Uint8Array): InspectResult {
  const format = detectFormat(u8);
  const r =
    format === 'png' ? inspectPng(u8)
    : format === 'jpeg' ? inspectJpeg(u8)
    : format === 'webp' ? inspectWebp(u8)
    : format === 'avif' || format === 'heic' ? inspectIsobmff(u8, format)
    : format === 'gif' ? inspectGif(u8)
    : { hasC2pa: false, hasAiMetadata: false, findings: ['unsupported image format'] };
  return { format, ...r };
}

/** Throws on unsupported or malformed input. */
export function clean(u8: Uint8Array, { stripAllMetadata = true }: { stripAllMetadata?: boolean } = {}): CleanResult {
  const format = detectFormat(u8);
  if (format === 'png') return { format, ...stripPng(u8, { stripAllText: stripAllMetadata }) };
  if (format === 'jpeg') return { format, ...stripJpeg(u8, { stripAllApp: stripAllMetadata }) };
  if (format === 'webp') return { format, ...stripWebp(u8, { stripAllMetadata }) };
  if (format === 'avif' || format === 'heic') return { format, ...stripIsobmff(u8, format, { stripAllMetadata }) };
  if (format === 'gif') return { format, ...stripGif(u8, { stripAllMetadata }) };
  throw new Error('unsupported image format (expected PNG, JPEG, WebP, AVIF, HEIC or GIF)');
}

export const SUPPORTED_IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.webp', '.avif', '.heic', '.heif', '.gif'];
